### ISSUE TITLE
new bibdata element breaks STS

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#1227]
In https://github.com/metanorma/metanorma/issues/416 , I have just introduced bibdata/ext/flavor, to capture in document metadata the Metanorma flavour used to compile it.

This is crashing the STS parser on the test in metanorma-iso:

````
 4) Metanorma::Iso::Processor generates STS from Metanorma XML
     Failure/Error:
       MnConvert.convert(in_fname,
                         { input_format: MnConvert::InputFormat::MN,
                           output_file: out_fname || "#{filename}.#{@suffix}" })
     
     RuntimeError:
       Input: XML (test.xml)
       Output: XML (test.sts.xml), format NISO STS
     
       Transforming...
       Validate XML against XSD NISO-STS-interchange-1-MathML3-XSD/NISO-STS-interchange-1-mathml3.xsd...
       /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iso/test.sts.xml is NOT valid reason:
       [ERROR] org.xml.sax.SAXParseException; lineNumber: 43; columnNumber: 9; cvc-complex-type.2.4.a: Invalid content was found starting with element 'flavor'. One of '{custom-meta-group}' is expected.
       [ERROR] org.xml.sax.SAXParseException; lineNumber: 45; columnNumber: 12; cvc-complex-type.2.3: Element 'std-meta' cannot have character [children], because the type's content type is element-only.
     # ./lib/isodoc/iso/sts_convert.rb:27:in `convert'
     # ./lib/metanorma/iso/processor.rb:63:in `output'
     # ./spec/metanorma/processor_spec.rb:166:in `block (2 levels) in <top (required)>'
````

**Comment by opoudjis** [comment]
Sorry to ask this, but please address this before Monday's release.

**Comment by Intelligent2013** [comment]
I've fixed the issue, but can't release a new version of `mnconvert`.

https://github.com/metanorma/mnconvert/actions/runs/11262712260/job/31319017665
```
cd tests/iso-8601-1 && metanorma site generate --agree-to-terms
[info]: Compiling /home/runner/work/mnconvert/mnconvert/tests/iso-8601-1/sources/iso-tc154-8601-1-en.adoc ...
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': /var/lib/gems/3.0.0/gems/coradoc-1.1.2/lib/coradoc/transformer.rb:221: syntax error, unexpected ',' (SyntaxError)
      opts = {id:,attribute_list:,contents:,sec...
                 ^
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/coradoc-1.1.2/lib/coradoc.rb:9:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-plugin-lutaml-0.6.6/lib/metanorma/plugin/lutaml/liquid/custom_filters.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-plugin-lutaml-0.6.6/lib/metanorma/plugin/lutaml/utils.rb:4:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-plugin-lutaml-0.6.6/lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb:7:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-plugin-lutaml-0.6.6/lib/metanorma-plugin-lutaml.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-standoc-2.8.11/lib/metanorma/standoc/macros.rb:14:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/metanorma-standoc-2.8.11/lib/metanorma/standoc/converter.rb:16:in `require_relative'
	from /var/lib/gems/3.0.0/gems/metanorma-standoc-2.8.11/lib/metanorma/standoc/converter.rb:16:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/metanorma-standoc-2.8.11/lib/metanorma-standoc.rb:3:in `require_relative'
	from /var/lib/gems/3.0.0/gems/metanorma-standoc-2.8.11/lib/metanorma-standoc.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-iso-2.7.10/lib/metanorma/iso/converter.rb:2:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/metanorma-iso-2.7.10/lib/metanorma-iso.rb:2:in `require_relative'
	from /var/lib/gems/3.0.0/gems/metanorma-iso-2.7.10/lib/metanorma-iso.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile_validate.rb:46:in `require_flavor'
	from /var/lib/gems/3.0.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile_validate.rb:30:in `load_flavor'
	from /var/lib/gems/3.0.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile_validate.rb:14:in `validate_type'
	from /var/lib/gems/3.0.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile_validate.rb:4:in `validate_options'
	from /var/lib/gems/3.0.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:42:in `options_process'
	from /var/lib/gems/3.0.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:29:in `compile'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/site_generator.rb:97:in `compile'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/site_generator.rb:32:in `block in generate'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/site_generator.rb:32:in `map'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/site_generator.rb:32:in `generate'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /var/lib/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor/invocation.rb:116:in `invoke'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor.rb:338:in `block in subcommand'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /var/lib/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /var/lib/gems/3.0.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli.rb:34:in `start'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/exe/metanorma:[25](https://github.com/metanorma/mnconvert/actions/runs/11262712260/job/31319017665#step:14:26):in `block in <top (required)>'
	from /var/lib/gems/3.0.0/gems/metanorma-cli-1.10.1/exe/metanorma:43:in `<top (required)>'
	from /usr/local/bin/metanorma:25:in `load'
	from /usr/local/bin/metanorma:25:in `<main>'
make: *** [Makefile:45: tests/iso-8601-1/_site/documents/iso-tc154-8601-1-en.xml] Error 1
```

I've tried to run locally `bundle exec metanorma site generate --agree-to-terms, but another error`:
```
[relaton] International Astronomical Union Resolution B1.9 (2000) does not have a recognised prefix
[relaton-iec] ("IEC 60050-113") fetching...
Fatal Error: Could not access http://www.iec.ch
C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:26:in `rescue in search': Could not access http://www.iec.ch (RelatonBib::RequestError)
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:23:in `search'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:97:in `search_filter'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:216:in `iecbib_get'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:46:in `get'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/processor.rb:17:in `get'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:187:in `fetch_doc'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:467:in `net_retry'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:436:in `new_bib_entry'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:400:in `check_bibliocache'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:64:in `fetch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:40:in `block in refs_iev2iec60050part'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:39:in `each'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:39:in `refs_iev2iec60050part'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:69:in `iev_cleanup'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/cleanup.rb:54:in `cleanup'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/base.rb:176:in `makexml'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/base.rb:127:in `document1'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/base.rb:116:in `document'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/utils.rb:13:in `convert'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/input/asciidoc.rb:18:in `process'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:59:in `process_input_adoc'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:42:in `process_input'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:33:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:89:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:29:in `block in generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:29:in `each'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:29:in `generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:24:in `generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/commands/site.rb:25:in `generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli.rb:34:in `start'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/src/metanorma:217:in `<main>'
C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/3.0.0/open-uri.rb:364:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/3.0.0/open-uri.rb:741:in `buffer_open'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/3.0.0/open-uri.rb:212:in `block in open_loop'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/3.0.0/open-uri.rb:210:in `catch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/3.0.0/open-uri.rb:210:in `open_loop'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/3.0.0/open-uri.rb:151:in `open_uri'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:96:in `results'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:88:in `block in get_results'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:84:in `each'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:84:in `reduce'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:84:in `get_results'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:56:in `hits'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/hit_collection.rb:21:in `initialize'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:24:in `new'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:24:in `search'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:97:in `search_filter'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:216:in `iecbib_get'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/iec_bibliography.rb:46:in `get'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iec-1.13.0/lib/relaton_iec/processor.rb:17:in `get'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:187:in `fetch_doc'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:467:in `net_retry'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:436:in `new_bib_entry'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:400:in `check_bibliocache'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-1.13.0/lib/relaton/db.rb:64:in `fetch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:40:in `block in refs_iev2iec60050part'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:39:in `each'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:39:in `refs_iev2iec60050part'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/relaton-iev-1.1.4/lib/relaton_iev.rb:69:in `iev_cleanup'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/cleanup.rb:54:in `cleanup'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/base.rb:176:in `makexml'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/base.rb:127:in `document1'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/base.rb:116:in `document'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/utils.rb:13:in `convert'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/input/asciidoc.rb:18:in `process'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:59:in `process_input_adoc'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:42:in `process_input'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:33:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:89:in `compile'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:29:in `block in generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:29:in `each'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:29:in `generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/site_generator.rb:24:in `generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/commands/site.rb:25:in `generate'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli.rb:34:in `start'
        from C:/Users/TestUser/AppData/Local/Temp/ocr8E28.tmp/src/metanorma:217:in `<main>'
```


How to repeat:
```
git clone https://github.com/metanorma/iso-8601-1
cd iso-8601-1
bundle update
bundle exec metanorma site generate --agree-to-terms
```

I'll try tomorrow again.

**Comment by Intelligent2013** [comment]
```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': /var/lib/gems/3.0.0/gems/coradoc-1.1.2/lib/coradoc/transformer.rb:221: syntax error, unexpected ',' (SyntaxError)
      opts = {id:,attribute_list:,contents:,sec...
                 ^
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

Ruby 3.1 allows the empty values in the hash, but `3.0.0` is using in the gems path `/var/lib/gems/3.0.0/gems/coradoc-1.1.2`.
