### ISSUE TITLE
PDF layout check: ISO/DIS 19135:2024 (check is for general layout and DIS)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1259]
ISO/DIS 19135:2024 has been published and we need to do a layout check for both the English and French version:

Source:
* https://github.com/metanorma/iso-19135

ISO PDFs:
* https://github.com/metanorma/mn-samples-iso-private/tree/main/reference-docs/ISO_DIS_19135_2024

There are some features we need to supplement in ISO:
* "ISO-CEN Parallel Processing"

<img width="494" alt="Screenshot 2024-12-11 at 9 45 48 PM" src="https://github.com/user-attachments/assets/374c4409-6308-45aa-8547-e372a8cd28c4" />

**Comment by Intelligent2013** [comment]
> There are some features we need to supplement in ISO:
>* "ISO-CEN Parallel Processing"

The similar ticket is https://github.com/metanorma/mn-native-pdf/issues/119.

@opoudjis could you add the document attribute `:iso-cen-parallel:` and these localized strings?
- en: `ISO/CEN PARALLEL PROCESSING`
- fr: `TRAITEMENT PARALLÈLE ISO/CEN`

**Comment by Intelligent2013** [comment]
I've added `document_2024.adoc` with additional document attributes in https://github.com/metanorma/iso-19135/pull/73.

`docidentifier type="iso-with-lang"` doesn't contain the language:
```xml
<docidentifier type="ISO" primary="true">ISO/DIS 19135</docidentifier>
<docidentifier type="iso-reference">ISO/DIS 19135:2024(E)</docidentifier>
<docidentifier type="URN">urn:iso:std:iso:19135:stage-40.00:en</docidentifier>
<docidentifier type="iso-undated">ISO/DIS 19135</docidentifier>
<docidentifier type="iso-with-lang">ISO/DIS 19135(en)</docidentifier>
<docidentifier type="iso-tc">XXX</docidentifier>
```
I don't understand the reason.

Rendered PDF:
![image](https://github.com/user-attachments/assets/03722daa-d6c4-454c-b564-60708f944242)


Original PDF:
![image](https://github.com/user-attachments/assets/2832e015-8cb8-493c-80c9-98e0fe5b0dd0)

**Comment by opoudjis** [comment]
> > There are some features we need to supplement in ISO:
> > 
> > * "ISO-CEN Parallel Processing"
> 
> The similar ticket is [metanorma/mn-native-pdf#119](https://github.com/metanorma/mn-native-pdf/issues/119).
> 
> @opoudjis could you add the document attribute `:iso-cen-parallel:` and these localized strings?
> 
> * en: `ISO/CEN PARALLEL PROCESSING`
> * fr: `TRAITEMENT PARALLÈLE ISO/CEN`

Done:

````xml
    <bibdata>
        <ext>
          <iso-cen-parallel>true</iso-cen-parallel>
        </ext>
      </bibdata>
````

**Comment by opoudjis** [comment]
@Intelligent2013 :

> I've added `document_2024.adoc` with additional document attributes in [metanorma/iso-19135#73](https://github.com/metanorma/iso-19135/pull/73).
> 
> `docidentifier type="iso-with-lang"` doesn't contain the language:
> 
> ```
> <docidentifier type="ISO" primary="true">ISO/DIS 19135</docidentifier>
> <docidentifier type="iso-reference">ISO/DIS 19135:2024(E)</docidentifier>
> <docidentifier type="URN">urn:iso:std:iso:19135:stage-40.00:en</docidentifier>
> <docidentifier type="iso-undated">ISO/DIS 19135</docidentifier>
> <docidentifier type="iso-with-lang">ISO/DIS 19135(en)</docidentifier>
> <docidentifier type="iso-tc">XXX</docidentifier>
> ```
> 
> I don't understand the reason.
> 
> Rendered PDF: ![image](https://private-user-images.githubusercontent.com/5559926/395633744-03722daa-d6c4-454c-b564-60708f944242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwODM3ODAsIm5iZiI6MTczNTA4MzQ4MCwicGF0aCI6Ii81NTU5OTI2LzM5NTYzMzc0NC0wMzcyMmRhYS1kNmM0LTQ1NGMtYjU2NC02MDcwOGY5NDQyNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMjMzODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTMyMjJkOTgwY2NhZGVjNTgwY2RmNGZmZDk3NDFhNjZjOWZmMTBiMmVlOGVkZjM4Y2E3MjM2OTU3MGM3YjMzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UNAt1jkbTCwBdZJXABWWJtLSQEC_pVBsgUrPcETCOvo)
> 
> Original PDF: ![image](https://private-user-images.githubusercontent.com/5559926/395633530-2832e015-8cb8-493c-80c9-98e0fe5b0dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwODM3ODAsIm5iZiI6MTczNTA4MzQ4MCwicGF0aCI6Ii81NTU5OTI2LzM5NTYzMzUzMC0yODMyZTAxNS04Y2I4LTQ5M2MtODBjOS05OGUwZmU1YjBkZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMjMzODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZiYjg0ZWFjNjIxODJjM2RiNDM4YmIzZjViYWZjOTNiMWQ4ZWQ0YTZhNjFkMGIyZGEzYzM2NDQyMTZkNzM4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-ZPtrZ15LxM9CZrFlbGIlK_A6QIGqefAwjhmEY4LuYk)

You mean, it doesn't contain the *year*.

That is intentional behaviour, and I'm confused why the metadata is the way it is.

If a document is indicated to be a draft, then there is no applicable publication year, and the year is deleted from the identifier. I consider this to be correct behaviour, and will not be removing it  without explicit instruction to from ISO.

Your document has `:docstage: 40`. That's why the year is being removed, and if anything it should be being stripped from all docidentifier instances. Remove that document identifier (so that `:docstage:` reverts to `60`), and the year reappears in the iso-with-lang docidentifier.

**Comment by Intelligent2013** [comment]
Gemfile:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"
```
The command `bundle exec metanorma -t iso -x presentation document_2024.adoc` fails:
```
...
Style: (ID _701e4485-e384-3fee-f565-e079239a00db): may contain ambiguous provision: If approved to retire, do we need to contact the source that originally proposed this entry?
Style: (ID _misccontainer_anchor_aliases): Table should have title
Fatal Error: uninitialized constant Metanorma::Standoc::Validate::Iev

        @iev = Iev::Db.new(@iev_globalname, @iev_localname) unless @no_isobib
               ^^^
Did you mean?  Metanorma::Iec
               IEV
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate_term.rb:10:in `init_iev': uninitialized constant Metanorma::Standoc::Validate::Iev (NameError)

        @iev = Iev::Db.new(@iev_globalname, @iev_localname) unless @no_isobib
               ^^^
Did you mean?  Metanorma::Iec
               IEV
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate_term.rb:15:in `iev_validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate.rb:20:in `content_validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-138a1aa0fa69/lib/metanorma/iso/validate.rb:162:in `content_validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-138a1aa0fa69/lib/metanorma/iso/validate.rb:197:in `validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:101:in `makexml'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:43:in `document1'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:32:in `document'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/utils.rb:13:in `convert'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.23/lib/asciidoctor/document.rb:956:in `convert'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.23/lib/asciidoctor/convert.rb:120:in `convert'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/input/asciidoc.rb:13:in `process'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/processor/processor.rb:21:in `input_to_isodoc'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:73:in `process_input_adoc'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:55:in `process_input'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:31:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:272:in `compile_document'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:62:in `block in compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:62:in `each'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:62:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli.rb:34:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/exe/metanorma:25:in `block in <top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/exe/metanorma:43:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<main>'
```

**Comment by Intelligent2013** [comment]
I've added the separate issue.

**Comment by Intelligent2013** [comment]
> 
> Done:
> 
> ```
>     <bibdata>
>         <ext>
>           <iso-cen-parallel>true</iso-cen-parallel>
>         </ext>
>       </bibdata>
> ```

@opoudjis thank you!
ISO XSLT updated.

> You mean, it doesn't contain the _year_.

@opoudjis  yes, I mean the 'year'.
I'm  confused a bit. Currently, for the latest layout '2024' (`document-scheme` is `2024`) I get the Reference number from `<docidentifier type="iso-with-lang">ISO/DIS 19135(en)</docidentifier>`. Also, there is `<docidentifier type="iso-reference">ISO/DIS 19135:2024(E)</docidentifier>`, but language is one letter value `E`, therefore I use `docidentifier type="iso-with-lang"`.

My goal in this ticket is updating ISO XSLT to render the PDF identical to the original PDF:
https://github.com/metanorma/mn-samples-iso-private/tree/main/reference-docs/ISO_DIS_19135_2024.
The original PDF has stage:
![image](https://github.com/user-attachments/assets/14785cae-e27d-4a0b-89f7-a585c87e7702)

and the Reference number with `/DIS` and year:
![image](https://github.com/user-attachments/assets/265cad86-d54c-4d6c-b7ec-1a721e3f90a9)

Is there a way to achieve such data via the document attributes?
Or this source ISO  PDF document is wrong?

**Comment by Intelligent2013** [comment]
The French rendered PDF has English stage name:
![image](https://github.com/user-attachments/assets/6874c9ed-8ca5-4301-84c3-8ae022290531)
Original PDF:
![image](https://github.com/user-attachments/assets/932b8103-9863-4631-aa5a-dac92e7983d0)

ISO XSLT reads this value from `/iso-standard/bibdata/ext/stagename`:
```xml
<stagename abbreviation="DIS">Draft International Standard</stagename>
```
but need to read from `/iso-standard/bibdata/status/stage`:
```xml
<stage abbreviation="DIS" language="fr">Brouillon de la norme internationale</stage>
```
but in any base there is a difference between the original title `PROJET Norme internationale` and from the localized string `Brouillon de la norme internationale`.

Also there are differences between voting dates titles:
- original PDF:
![image](https://github.com/user-attachments/assets/22954580-26e6-48cd-b06f-446634d1ab85)

- rendered PDF:
![image](https://github.com/user-attachments/assets/08124050-e090-47b9-abef-2e6ab401f60f)

Currently, the draft comments is the hard-coded text in ISO XSLT:
![image](https://github.com/user-attachments/assets/5e642518-93aa-4492-8277-21ff7a048e76)

![image](https://github.com/user-attachments/assets/9da118aa-eaa5-4880-a606-db9c14f06d5e)

We need to add them as localized strings in the metanorma-iso.
I'll add the tickets to track the issues separaterely.

**Comment by Intelligent2013** [comment]
Original PDF:
- cover page
![image](https://github.com/user-attachments/assets/a87f17b1-9462-48ff-94f1-7ad8b12309f1)

- main section 1st page contains `de` after `PROJET`:
![image](https://github.com/user-attachments/assets/198e459b-1ebd-47a8-8b3f-8b7195806292)

Is it feature of French layout and do we need to support both titles?

**Comment by ronaldtse** [comment]
@opoudjis the following statement is untrue. 

> If a document is indicated to be a draft, then there is no applicable publication year, and the year is deleted from the identifier. I consider this to be correct behaviour, and will not be removing it without explicit instruction to from ISO.

All ISO deliverable drafts have year in their identifier.

**Comment by ronaldtse** [comment]
Basically, the “with year” (dated) and “without year” (undated) identifiers should *always* be provided.

**Comment by opoudjis** [comment]
@Intelligent2013 Actioned.

**Comment by Intelligent2013** [comment]
- [ ] dashes between the date components should be in non-bold style:
![Image](https://github.com/user-attachments/assets/4dda291f-6591-4a5c-885d-70793aa52fb5)

**Comment by Intelligent2013** [comment]
- [ ] stage should be uppercased
Original PDF 'en':
![Image](https://github.com/user-attachments/assets/f9f44763-27a7-45ea-9faf-dc111f8c69ef)
Rendered PDF 'en':
![Image](https://github.com/user-attachments/assets/cf9490fc-3aeb-4389-a0be-5e32db1f8ddf)

- [ ] differences between cover page stage and main section first page stage:
Original PDF:
  - cover page
![image](https://github.com/user-attachments/assets/a87f17b1-9462-48ff-94f1-7ad8b12309f1)
  - main section 1st page contains `de` after `PROJET`:
![image](https://github.com/user-attachments/assets/198e459b-1ebd-47a8-8b3f-8b7195806292)

**Comment by Intelligent2013** [comment]
@opoudjis there are two questions.

1. currently, French stage is:
```xml
<stage abbreviation="DIS" language="fr">Brouillon de la norme internationale</stage>
```
but ISO uses the string `Projet Norme internationale`.
Is there a reason to use `Brouillon de la norme internationale` or just translated manually 'Draft International Standard'?. Could you change it to `Projet Norme internationale`?


2. Is it possible to add two additional elements:
In English XML:
```xml
<stage abbreviation="DIS" language="en" objective="coverpage">DRAFT<br/>International Standard</stage>
<stage abbreviation="DIS" language="en" objective="firstpage">DRAFT International Standard</stage>
```
Note: first `stage` contains break between stage and document type.

In French XML:
```xml
<stage abbreviation="DIS" language="fr" objective="coverpage">PROJET<br/>Norme internationale</stage>
<stage abbreviation="DIS" language="fr" objective="firstpage">PROJET de Norme internationale</stage>
```

Example:
```xml
<status>
	<stage abbreviation="DIS" language="">40</stage>
	<stage abbreviation="DIS" language="en">Draft International Standard</stage>
	<stage abbreviation="DIS" language="en" objective="coverpage">DRAFT<br/>International Standard</stage>
	<stage abbreviation="DIS" language="en" objective="firstpage">DRAFT International Standard</stage>
	<substage>00</substage>
</status>
```

**Comment by opoudjis** [comment]
1. Fixing Brouillon, which was indeed me guessing.
2. As with all XML changes, I now have to create a separate ticket for the proposal.

**Comment by Intelligent2013** [comment]
ISO XSLT should process both variants:
- for non-draft document (only one `stage` with `language="en"`):
```xml
<status>
	<stage language="">60</stage>
	<stage language="en">International Standard</stage>
	<substage>60</substage>
</status>
```
- for draft variants (two `stage` with `language="en"`)
```xml
<status>
	<stage abbreviation="DIS" language="">40</stage>
	<stage abbreviation="DIS" language="">Draft International Standard</stage>
	<stage abbreviation="DIS" language="en" type="firstpage">DRAFT International Standard</stage>
	<stage abbreviation="DIS" language="en" type="coverpage">DRAFT<br/>International Standard</stage>
	<substage>00</substage>
</status>
```

**Comment by opoudjis** [comment]
When I compile a document with 60, 60, I get in Presentation XML:

````
<status>
<stage language="">60</stage><stage language="en">International Standard</stage>
<substage>60</substage>
</status>
````

When I compile a document with 40, 00, I get:

````
<status>
<stage abbreviation="DIS" language="">40</stage>
<stage abbreviation="DIS" language="">Draft International Standard</stage>
<stage abbreviation="DIS" language="en" type="firstpage">DRAFT International Standard</stage>
<stage abbreviation="DIS" language="en" type="coverpage">DRAFT<br/>International Standard</stage>
<substage>00</substage>
</status>
````

So I'm confused: from what I know, I'm already producing what you've described, in branch fix/draft-coverpage

Btw FYI: because of today's breaking change to lutaml-model, please compile with the following Gemfile:

````
gem "html2doc", git: "https://github.com/metanorma/html2doc", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli", branch: "main"
````

**Comment by Intelligent2013** [comment]
> please compile with the following Gemfile:

@opoudjis  no changes. But currently ISO XSLT supports both variants. So don't urgent now.
And also, please restore the language attribute value in:
```
<stage abbreviation="DIS" language="">Draft International Standard</stage>
```
ISO XSLT updated in PR https://github.com/metanorma/mn-native-pdf/pull/831, ready to merge.

**Comment by opoudjis** [comment]
@Intelligent2013 OK, that was deliberate: I only supply the firstpage/coverpage alternatives if they exist, otherwise I leave them out. Are you saying you would rather see:

````
<stage language="en">International Standard</stage>
<stage language="en" type="coverpage">International Standard</stage>
<stage language="en" type="firstpage">International Standard</stage>
````

?

I have to say, I'm not enthusiastic about that, I think it's redundant.

Restoring language attribute, that was a bug.

**Comment by ronaldtse** [comment]
> I have to say, I'm not enthusiastic about that, I think it's redundant.

Better to be consistent across stages so there is less logic needed to differentiate...?

**Comment by opoudjis** [comment]
> > I have to say, I'm not enthusiastic about that, I think it's redundant.
> 
> Better to be consistent across stages so there is less logic needed to differentiate...?

The problem with that becomes, I end up moving the stage rendering types from config to code, because I can't guarantee that all i18n files have all stage rendering types. I really would rather not be hardcoding i18n options.

**Comment by opoudjis** [comment]
@Intelligent2013 Update please?

**Comment by Intelligent2013** [comment]
ISO XSLT updated.
The test document with `:iso-cen-parallel:` and added another attributes to reflect the cover page from the initial post: https://github.com/metanorma/iso-19135/blob/main/sources/iso-19135-2021/document_2024.adoc
All done.
