### ISSUE TITLE
Fatal Error: uninitialized constant Metanorma::Standoc::Validate::Iev

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1266]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1259

Source document: https://github.com/metanorma/iso-19135/tree/main/sources/iso-19135-2021

Error:
```
Style: (ID _26b7bd62-2ca8-acf1-e599-0779bf27da27): may contain ambiguous provision: Correctional changes, which may be urgent (e.g., issues related to security or
safety), could be substantive
Style: (ID _f8021a92-f9ab-63ea-0579-a1ffa7e5b72e): may contain ambiguous provision: 20240606 rwp fixed for circulation may need to check again EDITOR: See DK-106 new figure added as per discussion in EC2 (2024-05-23); however position of the new figure “Roles” needs to be fixed;
Fatal Error: uninitialized constant Metanorma::Standoc::Validate::Iev

        @iev = Iev::Db.new(@iev_globalname, @iev_localname) unless @no_isobib
               ^^^
Did you mean?  Metanorma::Iec
               IEV
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate_term.rb:10:in `init_iev': uninitialized constant Metanorma::Standoc::Validate::Iev (NameError)

        @iev = Iev::Db.new(@iev_globalname, @iev_localname) unless @no_isobib
               ^^^
Did you mean?  Metanorma::Iec
               IEV
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate_term.rb:15:in `iev_validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate.rb:20:in `content_validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.9.3/lib/metanorma/iso/validate.rb:162:in `content_validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.9.3/lib/metanorma/iso/validate.rb:197:in `validate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:101:in `makexml'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:43:in `document1'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:32:in `document'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/utils.rb:13:in `convert'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.23/lib/asciidoctor/document.rb:956:in `convert'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.23/lib/asciidoctor/convert.rb:120:in `convert'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/input/asciidoc.rb:13:in `process'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/processor/processor.rb:21:in `input_to_isodoc'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:73:in `process_input_adoc'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:55:in `process_input'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:31:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:272:in `compile_document'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:62:in `block in compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:62:in `each'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli/command.rb:62:in `compile'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/lib/metanorma/cli.rb:34:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/exe/metanorma:25:in `block in <top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.11.3/exe/metanorma:43:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<main>'
```

How to repeat:
```
git clone https://github.com/metanorma/iso-19135
cd iso-19135
bundle update
cd sources/iso-19135-2021
bundle exec metanorma -t iso -x presentation document.adoc 
```

**Comment by opoudjis** [comment]
Duplicates https://github.com/metanorma/metanorma-standoc/issues/951

This has been fixed in standoc, and is pending PR
