### ISSUE TITLE
Unable to generate ISO 10303-110 HTML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#359]
The XML gets generated, but the HTML fails to get generated. Maybe something to do with formulas.

```
bundle exec metanorma documents/iso-10303-110.xml
nil versions are discouraged and will be deprecated in Rubygems 4
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/metanorma)
NoMethodError: undefined method `text?' for nil:NilClass
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/isodoc-040a70439362/lib/isodoc/function/to_word_html.rb:139:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/isodoc-040a70439362/lib/isodoc/function/blocks.rb:162:in `block (2 levels) in formula_parse1'
```

**Comment by opoudjis** [comment]
Already addressed in https://github.com/metanorma/metanorma-standoc/issues/265
