### ISSUE TITLE
Concept mention not working in ISO vocabulary document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#517]
https://github.com/CalConnect/iso-34000

```
AsciiDoc Input: (XML Line 000100): Error: Term reference in `term[calendar-date]` missing:                 "calendar-date" is not defined in document
AsciiDoc Input: (XML Line 000100): Error: Term reference in `term[ordinal-date]` missing:                 "ordinal-date" is not defined in document
AsciiDoc Input: (XML Line 000100): Error: Term reference in `term[week-date]` missing:                 "week-date" is not defined in document
AsciiDoc Input: (XML Line 000142): Error: Term reference in `term[utc]` missing:                 "utc" is not defined in document
AsciiDoc Input: (XML Line 000142): Error: Term reference in `term[leap-second]` missing:                 "leap-second" is not defined in document
AsciiDoc Input: (XML Line 000166): Error: Term reference in `term[gregorian-calendar]` missing:                 "gregorian-calendar" is not defined in document
AsciiDoc Input: (XML Line 000169): Error: Term reference in `term[24-hour-clock-system]` missing:                 "24-hour-clock-system" is not defined in document
AsciiDoc Input: (XML Line 000187): Error: Term reference in `term[gregorian-calendar]` missing:                 "gregorian-calendar" is not defined in document
AsciiDoc Input: (XML Line 000187): Error: Term reference in `term[calendar-month]` missing:                 "calendar-month" is not defined in document
...
```

```
Style: (XML Line 000098): term citation not preceded with italicised term: timetime
Style: (XML Line 000098): term citation not preceded with italicised term: calendar systemcalendar system
Style: (XML Line 000098): term citation not preceded with italicised term: time scaletime scale
Style: (XML Line 000102): term citation not preceded with italicised term: instantinstant
Style: (XML Line 000102): term citation not preceded with italicised term: time intervaltime interval
Style: (XML Line 000102): term citation not preceded with italicised term: time scaletime scale
Style: (XML Line 000107): term citation not preceded with italicised term: clock systemclock system
Style: (XML Line 000107): term citation not preceded with italicised term: calendar systemcalendar system
...
```

```
Metanorma XML Syntax: (XML Line 000049:13): element "subdoctype" not allowed here; expected element "docsubtype", "editorialgroup" or "horizontal"
Metanorma XML Syntax: (XML Line 000144:71): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000157:94): element "strong" not allowed here; expected element "eref", "refterm", "renderterm", "termref" or "xref"
Metanorma XML Syntax: (XML Line 000157:183): element "concept" incomplete; expected element "eref", "refterm", "renderterm", "termref" or "xref"
Metanorma XML Syntax: (XML Line 000157:202): element "strong" not allowed here; expected element "eref", "refterm", "renderterm", "termref" or "xref"
Metanorma XML Syntax: (XML Line 000157:289): element "concept" incomplete; expected element "eref", "refterm", "renderterm", "termref" or "xref"
Metanorma XML Syntax: (XML Line 000157:312): element "strong" not allowed here; expected element "eref", "refterm", "renderterm", "termref" or "xref"
Metanorma XML Syntax: (XML Line 000157:393): element "concept" incomplete; expected element "eref", "refterm", "renderterm", "termref" or "xref"
Metanorma XML Syntax: (XML Line 000200:102): element "strong" not allowed here; expected element "eref", "refterm", "renderterm", "termref" or "xref"
```

And ends with a bang:

```
undefined method `name' for nil:NilClass
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.8.6/lib/isodoc/iso/presentation_xml_convert.rb:119:in `concept1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.7.0/lib/isodoc/presentation_function/inline.rb:159:in `block in concept'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.7.0/lib/isodoc/presentation_function/inline.rb:159:in `concept'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.7.0/lib/isodoc/presentation_xml_convert.rb:59:in `inline'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.7.0/lib/isodoc/presentation_xml_convert.rb:28:in `conversions'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.7.0/lib/isodoc/presentation_xml_convert.rb:18:in `convert1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.8.6/lib/isodoc/iso/presentation_xml_convert.rb:13:in `convert1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.7.0/lib/isodoc/convert.rb:164:in `convert'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.8.6/lib/metanorma/iso/processor.rb:60:in `output'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.6/lib/metanorma/compile.rb:212:in `block in process_extensions'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.6/lib/metanorma/compile.rb:199:in `each'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.6/lib/metanorma/compile.rb:199:in `process_extensions'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.6/lib/metanorma/compile.rb:31:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/compiler.rb:30:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/compiler.rb:35:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/site_generator.rb:81:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/site_generator.rb:28:in `each'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/site_generator.rb:28:in `generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/site_generator.rb:23:in `generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.11/lib/metanorma/cli/commands/site.rb:25:in `generate'
```

**Comment by ronaldtse** [comment]
There may be the following considerations for ISO:

* This is a vocabulary subtype document. Terms can exist in multiple clauses under the "terms and definition" header.
* In terms and definitions clauses, only the "first mention" of a term should be formatted as "_my term_ (1.1.1)", subsequent mentions are to be rendered as normal.
* In normal clauses, term mentions should not result in rendering differences.

**Comment by opoudjis** [comment]
> In terms and definitions clauses, only the "first mention" of a term should be formatted as "my term (1.1.1)", subsequent mentions are to be rendered as normal.

> In normal clauses, term mentions should not result in rendering differences.

This is capricious, but whatever.

**Comment by ronaldtse** [comment]
> This is capricious, but whatever.

See ISO house style...

**Comment by opoudjis** [comment]
Crash because error message `concept` instances need to be left alone, not postprocessed in Presentation XML.

**Comment by opoudjis** [comment]
Concepts are not being recognised, because the source is not recognised as terms.

The source is not being recognised as terms, because Metanorma is refusing to allow more than one Terms & Definitions section.

The document is vocabulary subtype, which means it should be allowing more than one Terms & Definitions section. Investigating.

**Comment by ronaldtse** [comment]
Using Git for metanorma-iso (fix/concept-err):

<img width="864" alt="Screenshot 2021-07-07 at 9 59 24 PM" src="https://user-images.githubusercontent.com/11865/124772521-b0c48d80-df6e-11eb-8662-11443c9876ac.png">

**Comment by ronaldtse** [comment]
Concept mentions that worked (seems that terms with single words work) have a missing space between the italicized term and the "(...)".

<img width="612" alt="Screenshot 2021-07-07 at 10 00 40 PM" src="https://user-images.githubusercontent.com/11865/124772677-d2be1000-df6e-11eb-86a3-8f8623680eaf.png">

**Comment by opoudjis** [comment]
Major refactoring needed to cope with multiple terms sections in a document.

**Comment by opoudjis** [comment]
Space between renderterm and crossreference indeed missed.

**Comment by opoudjis** [comment]
Remove validation check "term citation not preceded with italicised term": that is supplanted by automated concept rendering.
