### ISSUE TITLE
PDF: Requirements are highlighted with color incorrectly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#778]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/11865/187597212-29a3fce9-1c2c-4b30-903a-71894f2163d8.png">

There should have been no coloring of the header row.

**Comment by Intelligent2013** [comment]
@ronaldtse could you confirm that this render is ok?
![image](https://user-images.githubusercontent.com/5559926/187639821-df72ab0a-4e96-4528-bfca-c28628a9aadc.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 I would like to wait until the implementation of #777 to see how it looks. Thanks!

**Comment by Intelligent2013** [comment]
I've generated presentation XML with such Gemfile file:

```
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "features/modspec-iso"
gem "metanorma-utils", git: "https://github.com/metanorma/metanorma-utils", branch: "main"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "mn-requirements", git: "https://github.com/metanorma/mn-requirements", branch: "master"
gem "sassc"
```

and now PDF renders so:
![image](https://user-images.githubusercontent.com/5559926/188322474-4f9be40f-ec67-42a0-83d2-98aa00d9b0a0.png)
similar to Word.

**Comment by ronaldtse** [comment]
There are 2 issues:
1. The "Description" header for row 3 is not showing.
2. The "Provisions" header for row 4 should be aligned to top.

**Comment by Intelligent2013** [comment]
Something wrong happened, I can't generate the XML:
`git clone https://github.com/metanorma/iso-19135`
`cd iso-19135`
`bundle update`
`cd sources\iso-19135-2021`
`bundle exec metanorma -t iso -x presentation document.adoc`:
```
Traceback (most recent call last):
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/exe/metanorma:43:in `<top (required)>'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/exe/metanorma:25:in `block in <top (required)>'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli.rb:34:in `start'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:47:in `compile'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:47:in `each'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:47:in `block in compile'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:240:in `compile_document'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli.rb:17:in `load_flavors'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/flavor.rb:35:in `load_flavors'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/flavor.rb:47:in `load_flavors'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/flavor.rb:47:in `each'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/flavor.rb:48:in `block in load_flavors'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/flavor.rb:48:in `require'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.1.8/lib/metanorma-iso.rb:2:in `<top (required)>'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.1.8/lib/metanorma-iso.rb:2:in `require_relative'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.1.8/lib/metanorma/iso/converter.rb:2:in `<top (required)>'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.1.8/lib/metanorma/iso/converter.rb:2:in `require'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.2.2.1/lib/metanorma-standoc.rb:3:in `<top (required)>'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.2.2.1/lib/metanorma-standoc.rb:3:in `require_relative'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.2.2.1/lib/metanorma/standoc/converter.rb:11:in `<top (required)>'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.2.2.1/lib/metanorma/standoc/converter.rb:11:in `require_relative'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.2.2.1/lib/metanorma/standoc/validate.rb:8:in `<top (required)>'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.2.2.1/lib/metanorma/standoc/validate.rb:8:in `require'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/png-1.2.1/lib/png.rb:13:in `<top (required)>'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/png-1.2.1/lib/png.rb:14:in `<class:String>'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.6/lib/inline.rb:854:in `inline'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.6/lib/inline.rb:606:in `build'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.6/lib/inline.rb:606:in `chdir'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.6/lib/inline.rb:606:in `block in build'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.6/lib/inline.rb:606:in ``': No such file or directory - x86_64-w64-mingw32-gcc -shared  -O3 -fno-fast-math -fstack-protector-strong -I C:/Ruby27-x64/include
/ruby-2.7.0 -I C:/Ruby27-x64/include/ruby-2.7.0/x64-mingw32 -I C:/Ruby27-x64/include "C:/Users/TestUser/.ruby_inline/ruby-2.7.0/Inline_String_9a6686966a50705d94442f198bc2c408.c"   -Wl,--enable-auto-import -LC:/R
uby27-x64/lib -lx64-msvcrt-ruby270 -o "C:/Users/TestUser/.ruby_inline/ruby-2.7.0/Inline_String_9a6686966a50705d94442f198bc2c408.so" -L. -pipe -s -fstack-protector-strong  (Errno::ENOENT)
```
Will raise an issue.

**Comment by Intelligent2013** [comment]
This issue depends on https://github.com/metanorma/metanorma-iso/issues/796.

**Comment by Intelligent2013** [comment]
Resulted PDF (generated on Ubuntu):
![image](https://user-images.githubusercontent.com/5559926/196481440-df934c82-f0e4-40a5-9f95-d41994b31054.png)

> There are 2 issues:
> The "Description" header for row 3 is not showing.
> The "Provisions" header for row 4 should be aligned to top.

```xml
<table id="_" class="modspec" type="recommendclass">
	<name>Table 1 — Requirements class 1: Responsibilities of the register owner</name>
	<tbody>
		<tr>
			<td>Identifier</td>
			<td>
				<tt>/req/roles/register-owner</tt>
			</td>
		</tr>
		<tr>
			<td>Target type</td>
			<td>register owner</td>
		</tr>
		<tr>
			<td>Description</td>
			<td>
				<p id="_">Responsibilities of the register owner</p>
			</td>
		</tr>
		<tr>
			<td>Provisions</td>
			<td>
				<xref target="_>Requirement 1: Creation of a register specification</xref>
```

Currently, ISO XSLT renders left column aligned to middle. Will fix.

**Comment by Intelligent2013** [comment]
ISO XSLT updated:
![image](https://user-images.githubusercontent.com/5559926/196489114-ebb80f27-2ca6-48ae-abcb-d4b92d3da084.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
