### ISSUE TITLE
(URGENT) Crash when adding footnote to named reference tag

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#873]
According to documentation, we can add a footnote to a named reference tag.
https://www.metanorma.org/author/topics/document-format/bibliography/

<img width="672" alt="Screen Shot 2022-12-02 at 2 12 12 PM" src="https://user-images.githubusercontent.com/11865/205227133-b15e7ee4-debe-4e07-9a86-266fd117f8f6.png">

So in ISO/IEC 17025 we do this:

```adoc
[bibliography]
== Normative references

* [[[ISO_IEC_Guide_99_2007,(ISO/IEC Guide 99:2007 footnote:[Also known as JCGM 200])ISO/IEC Guide 99:2007]]], ISO/IEC Guide 99, International vocabulary of metrology -- Basic and general concepts and associated terms (VIM)

* [[[ISO_IEC_17000_2004,ISO/IEC 17000:2004]]], ISO/IEC 17000, Conformity assessment -- Vocabulary and general principles
```

However, this doesn't actually work and ends up with different broken results across formats:

HTML: (entire reference missing)
<img width="903" alt="Screen Shot 2022-12-02 at 2 14 24 PM" src="https://user-images.githubusercontent.com/11865/205227485-a59c5dd3-9e41-4785-9230-eb9ba1749c76.png">

Word: (footnote mangled in the named reference tag)
<img width="625" alt="Screen Shot 2022-12-02 at 2 13 28 PM" src="https://user-images.githubusercontent.com/11865/205227329-56dc5313-ee63-4744-a867-b002017d5e06.png">

PDF: (missing named reference tag)
<img width="574" alt="Screen Shot 2022-12-02 at 2 13 09 PM" src="https://user-images.githubusercontent.com/11865/205227290-9a5fcfb7-cf76-486a-a009-a49740e89c78.png">

This is the crash error trace:
```
undefined method `previous=' for nil:NilClass

        fn.children.first.previous = xdup
                         ^^^^^^^^^^^
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess_footnotes.rb:30:in `footnote_backlinks1'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess_footnotes.rb:41:in `block in footnote_backlinks'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess_footnotes.rb:38:in `each_with_index'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess_footnotes.rb:38:in `footnote_backlinks'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess.rb:29:in `html_cleanup'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess.rb:16:in `toHTML'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_function/postprocess.rb:11:in `postprocess'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/convert.rb:233:in `convert'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.6/lib/isodoc/html_convert.rb:26:in `convert'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.2.4/lib/metanorma/iso/processor.rb:49:in `output'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.3/lib/metanorma/compile.rb:149:in `process_output_threaded'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.3/lib/metanorma/compile.rb:141:in `block in process_exts1'
```

See this PR to reproduce:
* https://github.com/metanorma/iso-17025/pull/2

**Comment by opoudjis** [comment]
Fix has to now involve biblio-tag...

**Comment by opoudjis** [comment]
Previous implementation was naive. Now extracting footnote out of docidentifier before further processing, and concatenating it to any date footnotes.
