### ISSUE TITLE
Failure in generating STS on Ubuntu using Tebako

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#944]
Original issue:
* https://github.com/metanorma/iso-19135/issues/33

```
java -Xss5m -Xmx2048m -jar /tmp/packed-mn-20230308-2089-1dgk0hq/mn2pdf.jar --xml-file "/home/runner/work/iso-19135/iso-19135/_site/documents/iso-19135-2021/document.presentation.xml" --xsl-file "/tmp/packed-mn-20230308-2089-1dgk0hq/iso.international-standard.xsl" --pdf-file "/home/runner/work/iso-19135/iso-19135/_site/documents/iso-19135-2021/document.pdf" --param baseassetpath="/home/runner/work/iso-19135/iso-19135/sources/iso-19135-2021" --syntax-highlight  --font-manifest "/tmp/fontist_locations20230308-2089-vjbpkt.yml"
wrong number of arguments (given 2, expected 3..4)
/__tebako_memfs__/local/metanorma:133:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.3.5/lib/isodoc/iso/sts_convert.rb:27:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.3.5/lib/metanorma/iso/processor.rb:61:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:149:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:141:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.57/lib/mn2pdf.rb:79:in `mn2pdf'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.57/lib/mn2pdf.rb:54:in `block in convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.57/lib/mn2pdf.rb:100:in `block in dump_fontist_manifest_locations'
/__tebako_memfs__/lib/ruby/2.7.0/tempfile.rb:332:in `create'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.57/lib/mn2pdf.rb:96:in `dump_fontist_manifest_locations'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.57/lib/mn2pdf.rb:52:in `convert'
/__tebako_memfs__/local/metanorma:119:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.4.4/lib/metanorma/output/xslfo.rb:10:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.4.4/lib/isodoc/xslfo_convert.rb:59:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.3.5/lib/metanorma/iso/processor.rb:58:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:149:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:141:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

@maxirmx @CAMOBAP can you please help check why we get this error? Specifically:

```
wrong number of arguments (given 2, expected 3..4)
/__tebako_memfs__/local/metanorma:133:in `convert'
```

**Comment by CAMOBAP** [comment]
There is a mess in stack trace because of `worker_pool`. It issue doesn't looks related to mn2pdf but probably related to mnconvert. Investigation in progress...
