### ISSUE TITLE
PDF ISO 10303-104: The current document is unable to create an element of the requested type

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#953]
The source issue: https://github.com/metanorma/metanorma-iso/issues/952

The error occurs when .png replaced by .svg images:
```
org.w3c.dom.DOMException: The current document is unable to create an element of the requested type (namespace: http://www.w3.org/2000/svg, name: keep-together_within-line).
        at org.apache.batik.dom.AbstractNode.createDOMException(AbstractNode.java:408)
        at org.apache.batik.anim.dom.SVGDOMImplementation.createElementNS(SVGDOMImplementation.java:201)
```

**Comment by Intelligent2013** [comment]
XSLT mistakenly adds `<keep-together_within-line>` into SVG content:
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" viewBox="0 0 588 420" height="420" width="588" xml:space="preserve" id="svg2" version="1.1">
	<metadata id="metadata8_inject_0">
		<rdf:RDF>
			<cc:Work rdf:about="">
				<dc:format>
					<keep-together_within-line>image/svg</keep-together_within-line>+xml</dc:format>
				<dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
			</cc:Work>
		</rdf:RDF>
	</metadata>
```
