### ISSUE TITLE
Issue with citing "(all parts)" with custom text (+ rethink reference label syntax)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#960]
In ISO 80000-1:2022 there is a bibliographic reference to "ISO 31 (all parts)", encoded as follows:

```adoc
[bibliography]
== Bibliography

* [[[iso31,(ISO 31 (all parts)footnote:[ISO 31 series is withdrawn and replaced by ISO/IEC 80000 series.])ISO 31 (all parts)]]]
...
```

This syntax is technically correct, but is rendered as follows:

Word:
<img width="605" alt="Screenshot 2023-03-27 at 10 32 37 AM" src="https://user-images.githubusercontent.com/11865/227826619-c0d58e4f-1977-4451-8df5-390f1038397e.png">

PDF:
<img width="544" alt="Screenshot 2023-03-27 at 10 32 58 AM" src="https://user-images.githubusercontent.com/11865/227826665-a96b2186-b205-4610-9dc8-b7fe1b08613d.png">

The root cause is that the bibliographic label syntax does not well handle parentheses in the case of `(all parts)`.

A better parser could get this working but perhaps a re-think of the reference label syntax should be done.

Document:
* https://github.com/metanorma/iso-iec-80000/pull/6

**Comment by opoudjis** [comment]
The current syntax is:

````
REFLABEL =  `nofetch(`               `)`  /* cite but do not fetch from relaton */
               `hidden(`           `)`    /* do not display citation */
                 `dropid(`  ID  `)`       /* do not display identifier */
    

ID = CODE | /* fetch if recognised */
\d+ | /* autoincrement number, no fetch */
\( USRLBL \) | /* user-supplied label, no fetch */
\( USRLBL \) CODE | /* combinations of the above */
\( \d+ \) CODE | /* combinations of the above */
repo:\(repository-name/document-entry,CODE\) |  /* fetch, assign to document in a repository, including collections */
path:\(LINK,CODE\) /* fetch, assign to a file path */

CODE = PUBLISHER? IDENTIFIER (\(all parts\))?

````

I like this syntax, and although parenthesis is overused, it could be remedied with appropriate use of contextual parsers. However, a more explicit markup system should indeed be available. I propose the following, as key-value pairs, comma-delimited, parsed by CSV:

````
nofetch=true|false
hidden=true|false
dropid=true|false
repo=repositoryname/document-entry
path=link
number=x
usrlabel=x
code=x
````

If the final entry has no key, then it is assumed to be the code. So for example,

````
* [[[ref1,nofetch=true,dropid=true,path=../../files/repo.adoc,number=1,userlabel=CerMon,ISO 122 (all parts)]]]
````

**Comment by opoudjis** [comment]
No need for the latter: this is processed fine:

````
* [[[iso124,ISO 124:—]]]{blank}footnote:[The standard is in press] _Standard_
````

So enter:

````
* [[[iso31,ISO 31 (all parts)]]]{blank}footnote:[ISO 31 series is withdrawn and replaced by ISO/IEC 80000 series.] 
````

This works in the general case. In this specific case though, there is already a footnote provided in the ISO 31 entry, with the text "Withdrawn", which we need to overwrite with the footnote text. This is normally doable by supplying span:note[], but ISO references currently are ignoring spans; will fix that.

**Comment by opoudjis** [comment]
Fixed, but for this to work, you need to supply the type of the note, which in the relaton entry represents the footnote, so that it is replaced and the note type is retained:

````
* [[[iso31,ISO 31 (all parts)]]] span:note.Unpublished-Status[ISO 31 series is withdrawn and replaced by ISO/IEC 80000 series.] 
````

Have just confirmed it works:

<img width="479" alt="Screenshot 2023-05-05 at 01 45 21" src="https://user-images.githubusercontent.com/1911039/236345341-921ed7e1-d8a5-405f-9178-969562daca30.png">

**Comment by ronaldtse** [comment]
The resulting reference is not correctly shown and is crashing:
<img width="902" alt="Screenshot 2023-05-12 at 2 49 24 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/e8f94b07-ec72-49ed-a043-f9fcdc7bc49d">


```
undefined method `text?' for nil:NilClass

          s.next.text? or next
                ^^^^^^
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.4/lib/isodoc/word_function/postprocess.rb:101:in `block in word_tab_clean'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.4-arm64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.4-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.4-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.4/lib/isodoc/word_function/postprocess.rb:100:in `word_tab_clean'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.4/lib/isodoc/word_function/postprocess.rb:60:in `word_cleanup'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-3dcbd9081acd/lib/isodoc/iso/word_cleanup.rb:137:in `word_cleanup'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-3dcbd9081acd/lib/isodoc/iso/word_dis_cleanup.rb:202:in `word_cleanup'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-3dcbd9081acd/lib/isodoc/iso/word_dis_convert.rb:70:in `toWord'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.4/lib/isodoc/word_function/postprocess.rb:13:in `postprocess'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.4/lib/isodoc/convert.rb:161:in `convert'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.4/lib/isodoc/word_convert.rb:20:in `convert'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-3dcbd9081acd/lib/isodoc/iso/word_convert.rb:63:in `convert'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-3dcbd9081acd/lib/isodoc/iso/word_convert.rb:61:in `convert'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-3dcbd9081acd/lib/metanorma/iso/processor.rb:55:in `output'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/compile.rb:150:in `process_output_threaded'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/compile.rb:142:in `block in process_exts1'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/worker_pool.rb:9:in `loop'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/worker_pool.rb:8:in `catch'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-4db65230646a/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

**Comment by ronaldtse** [comment]
Sorry for jumping the gun -- ISO 80000-1 wasn't updated to use the new syntax. Thanks!

<img width="882" alt="Screenshot 2023-05-12 at 2 51 45 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/e8702288-d328-49f9-b64b-bb58ea7b66c5">
